apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "placeholder"
      auth:
        serviceAccount:
          secretRef:
            name: external-secrets-service-account
            namespace: external-secrets
      mount: kubernetes
      role: external-secrets-role