apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin-password
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store
  target:
    name: jenkins-credentials
    creationPolicy: CreateIfNotExists
  data:
  - secretKey: JENKINS_ADMIN_PASSWORD
    remoteRef:
      key: secret/data/jenkins/admin-password
      property: admin-password